language: node_js
node_js: node
branches:
  only:
    - master
    - develop
addons:
  chrome: stable
cache:
  directories:
    - 'node_modules'
    - 'ng-blog/node_modules'
before_install:
install:
script:
before_deploy:
